import { build } from 'esbuild';
import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
const outputFile = new URL('../ui/panel-bundle.mts', import.meta.url);
const manifestFile = new URL('../ui/panel-build.json', import.meta.url);
const result = await build({ absWorkingDir: root, entryPoints: ['ui/panel-app.mts'], bundle: true, platform: 'browser', format: 'iife', target: 'es2022', minify: true, write: false, legalComments: 'inline', charset: 'utf8' });
const notices = await readFile(new URL('../ui/THIRD_PARTY_NOTICES.txt', import.meta.url), 'utf8');
if (notices.includes('*/')) throw new Error('invalid_license_comment');
const script = (`/*!\n${notices}\n*/\n` + result.outputFiles[0].text).replace(/<\/script/gi, '<\\/script');
const hash = value => createHash('sha256').update(value).digest('hex');
const template = await readFile(new URL('../ui/panel.html', import.meta.url), 'utf8');
if (template.split('<!-- PANEL_SCRIPT -->').length !== 2) throw new Error('invalid_panel_script_marker');
// A function replacement keeps SDK strings such as "$&" from expanding as replace tokens.
const html = template.replace('<!-- PANEL_SCRIPT -->', () => `<script>${script}</script>`);
const contentHash = hash(html), uri = `ui://stats-synthetic-loop/tunnel-panel-${contentHash}.html`;
const manifest={html_sha256:contentHash,script_sha256:hash(script),html_bytes:Buffer.byteLength(html),script_bytes:Buffer.byteLength(script)};
if(process.argv.includes('--record'))await writeFile(manifestFile,JSON.stringify(manifest,null,2)+'\n');
else if(JSON.stringify(JSON.parse(await readFile(manifestFile,'utf8')))!==JSON.stringify(manifest))throw new Error('panel_build_manifest_changed: review source/lockfile, then run build-panel.mjs --record');
const output = '// Generated by scripts/build-panel.mjs. Official SDK dependencies are build-time only.\n'
  + Object.entries({ PANEL_SCRIPT: script, PANEL_BUILD_HASH: hash(script), PANEL_HTML: html, PANEL_CONTENT_HASH: contentHash, PANEL_URI: uri })
    .map(([key, value]) => `export const ${key} = ${JSON.stringify(value)};\n`).join('');
if (process.argv.includes('--check')) {
  if (await readFile(outputFile, 'utf8') !== output) throw new Error('panel_bundle_out_of_date: run npm run build:panel');
} else await writeFile(outputFile, output);
console.log(JSON.stringify({ panel_bytes: Buffer.byteLength(html), script_bytes: Buffer.byteLength(script), sha256: contentHash }));
